### PR TITLE
when-guarded versions of -> and ->> macros

### PR DESCRIPTION
**Pull request by eschulte**

### CODE REVIEW

**Comment by vindarel** [comment]
Hi @nightfly19, any chance in seeing this merged ? Thanks !

**Comment by eschulte** [comment]
Is this repository still maintained and are the pull requests monitored?

**Comment by eschulte** [comment]
Switched to re-implementation of the whole library in https://github.com/eschulte/cl-arrowz

**Comment by vindarel** [comment]
Cool. Just in case, if that helps, I have seen dead projects taken over by someone else and replaced in QL. It just a matter of telling QL's maintainer. So you could keep the cl-arrows name (if that's of importance).

**Comment by eschulte** [comment]
Actually, FWIW I've since noticed the arrow-macros package which I believe is a better alternative to either of these options.

**Pull request closed without merging**
